version: '3'
services:
  bot:
   build: .
   depends_on:
    - postgres
    - redis
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ./redis:/data
