version: '3'
services:
  bot:
    build: .
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${HOME}/pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    volumes:
      - ${HOME}/redis:/data
    restart: always
  nginx:
    image: "nginx"
    ports:
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - SERVER_IP=${WEBHOOK_HOST}
    depends_on:
      - postgres
      - redis
      - bot
    restart: always
